const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Tilemap,
		C3.Plugins.Camera3D,
		C3.Plugins.TiledBg,
		C3.Behaviors.solid,
		C3.Plugins.Sprite,
		C3.Plugins.Mouse,
		C3.Plugins.Keyboard,
		C3.Behaviors.Car,
		C3.Plugins.Shape3D,
		C3.Plugins.Text,
		C3.Behaviors.Bullet,
		C3.Plugins.Audio,
		C3.Behaviors.Turret,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Audio.Acts.FadeVolume,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.Mouse.Acts.SetCursor2,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.System.Acts.ResetEventVar,
		C3.Plugins.Camera3D.Acts.LookParallelToLayout,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Behaviors.Car.Acts.SetAcceleration,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Behaviors.Car.Acts.SetDeceleration,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Sprite.Acts.AddInstanceVar,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Behaviors.Car.Acts.SetSpeed,
		C3.Plugins.Text.Cnds.CompareInstanceVar,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Shape3D.Acts.SetVisible,
		C3.Plugins.TiledBg.Cnds.CompareInstanceVar,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Shape3D.Cnds.OnCollision,
		C3.Plugins.Shape3D.Acts.SetInstanceVar,
		C3.Plugins.Shape3D.Acts.SetTowardPosition,
		C3.Plugins.TiledBg.Exps.X,
		C3.Plugins.TiledBg.Exps.Y,
		C3.Plugins.Shape3D.Cnds.CompareInstanceVar,
		C3.Behaviors.Bullet.Acts.SetSpeed
	];
};
self.C3_JsPropNameTable = [
	{Mosaico: 0},
	{Câmera3D: 0},
	{Sólido: 0},
	{PlanoDeFundoEmBlocos: 0},
	{Sprite3: 0},
	{Sprite4: 0},
	{Sprite5: 0},
	{Mouse: 0},
	{Sprite6: 0},
	{Sprite7: 0},
	{Sprite8: 0},
	{Teclado: 0},
	{f1: 0},
	{ValidarVoltas: 0},
	{Minutos: 0},
	{Segundos: 0},
	{Carro: 0},
	{player: 0},
	{Forma3D: 0},
	{Forma3D2: 0},
	{parede: 0},
	{QualContador: 0},
	{ContadorDeVoltas: 0},
	{QualTexto: 0},
	{Texto: 0},
	{QualQuadrado: 0},
	{BlocoIA: 0},
	{Projétil: 0},
	{Competidor1: 0},
	{Sprite: 0},
	{Sprite2: 0},
	{Áudio: 0},
	{Sprite9: 0},
	{Sprite10: 0},
	{Forma3D3: 0},
	{Forma3D4: 0},
	{Forma3D5: 0},
	{QualQuadrado3: 0},
	{Competidor3: 0},
	{QualQuadrado2: 0},
	{Competidor2: 0},
	{QualQuadrado5: 0},
	{Competidor5: 0},
	{QualQuadrado4: 0},
	{Competidor4: 0},
	{Flores: 0},
	{arquiban: 0},
	{Forma3D7: 0},
	{Arvore: 0},
	{PlanoDeFundoEmBlocos2: 0},
	{pedra: 0},
	{Forma3D11: 0},
	{Forma3D12: 0},
	{Forma3D13: 0},
	{Forma3D14: 0},
	{Forma3D15: 0},
	{Forma3D16: 0},
	{Canhão: 0},
	{nuvem: 0},
	{Forma3D17: 0},
	{raio: 0},
	{Forma3D8: 0},
	{start: 0},
	{Forma3D10: 0},
	{finish: 0},
	{agua: 0},
	{um: 0},
	{dois: 0},
	{tres: 0},
	{vai: 0},
	{Sprite11: 0},
	{Contar: 0},
	{CheckPointsIA: 0},
	{Voltas: 0},
	{CheckPointsIA2: 0},
	{Voltas2: 0},
	{CheckPointsIA3: 0},
	{Voltas3: 0}
];

self.InstanceType = {
	Mosaico: class extends self.ITilemapInstance {},
	Câmera3D: class extends self.IInstance {},
	PlanoDeFundoEmBlocos: class extends self.ITiledBackgroundInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	Teclado: class extends self.IInstance {},
	f1: class extends self.ISpriteInstance {},
	player: class extends self.ISpriteInstance {},
	Forma3D: class extends self.I3DShapeInstance {},
	Forma3D2: class extends self.I3DShapeInstance {},
	parede: class extends self.ISpriteInstance {},
	ContadorDeVoltas: class extends self.ITiledBackgroundInstance {},
	Texto: class extends self.ITextInstance {},
	BlocoIA: class extends self.ITiledBackgroundInstance {},
	Competidor1: class extends self.I3DShapeInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Áudio: class extends self.IInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	Sprite10: class extends self.ISpriteInstance {},
	Forma3D3: class extends self.I3DShapeInstance {},
	Forma3D4: class extends self.I3DShapeInstance {},
	Forma3D5: class extends self.I3DShapeInstance {},
	Competidor3: class extends self.I3DShapeInstance {},
	Competidor2: class extends self.I3DShapeInstance {},
	Competidor5: class extends self.I3DShapeInstance {},
	Competidor4: class extends self.I3DShapeInstance {},
	Flores: class extends self.I3DShapeInstance {},
	arquiban: class extends self.I3DShapeInstance {},
	Forma3D7: class extends self.I3DShapeInstance {},
	Arvore: class extends self.I3DShapeInstance {},
	PlanoDeFundoEmBlocos2: class extends self.ITiledBackgroundInstance {},
	pedra: class extends self.I3DShapeInstance {},
	Forma3D11: class extends self.I3DShapeInstance {},
	Forma3D12: class extends self.I3DShapeInstance {},
	Forma3D13: class extends self.I3DShapeInstance {},
	Forma3D14: class extends self.I3DShapeInstance {},
	Forma3D15: class extends self.I3DShapeInstance {},
	Forma3D16: class extends self.I3DShapeInstance {},
	nuvem: class extends self.I3DShapeInstance {},
	Forma3D17: class extends self.I3DShapeInstance {},
	raio: class extends self.I3DShapeInstance {},
	Forma3D8: class extends self.I3DShapeInstance {},
	start: class extends self.I3DShapeInstance {},
	Forma3D10: class extends self.I3DShapeInstance {},
	finish: class extends self.I3DShapeInstance {},
	agua: class extends self.I3DShapeInstance {},
	um: class extends self.ITextInstance {},
	dois: class extends self.ITextInstance {},
	tres: class extends self.ITextInstance {},
	vai: class extends self.ITextInstance {},
	Sprite11: class extends self.ISpriteInstance {}
}